### ISSUE TITLE
Custom favicon

### ISSUE THREAD

**Issue by AryanJ-NYC** [AryanJ-NYC/reactandtypescript.dev#4]
# User Story
As a developer, I want a favicon that reflects this guide's purpose (React and TypeScript).

# Acceptance Criteria
A new `favicon.ico` in `/public` that reflects `reactandtypescript.dev`.

Added configuration to display the favicon ([example](https://github.com/doczjs/docz/issues/39#issuecomment-440577061)).

**Comment by hereticaneue** [comment]
Any preferences for the favicon appearance? Some combo of the React and TypeScript logos? I can try to make something acceptable!

**Comment by hereticaneue** [comment]
Something like this...?
![React_TypeScript_Favicon](https://user-images.githubusercontent.com/45669137/96767388-143b6a80-13a2-11eb-939b-d01707f031ad.png)

**Comment by AryanJ-NYC** [comment]
It should include a little indication of TypeScript, too. But I like where it's heading!

**Comment by hereticaneue** [comment]
Oh snap, forgot that part lol. Here's a couple updated options...
![React_TypeScript_Favicon_black](https://user-images.githubusercontent.com/45669137/96778072-c11ce400-13b0-11eb-918c-4ca9ac58ebfa.png)
![React_TypeScript_Favicon_blue](https://user-images.githubusercontent.com/45669137/96778079-c1b57a80-13b0-11eb-9d03-ec1068e1b87d.png)

**Comment by AryanJ-NYC** [comment]
I _love_ the bottom one. Would you like to take care of the pull request? I'm more than happy to help you along if necessary.

If you don't feel comfortable, I'd still _LOVE_ to credit you somehow.

**Comment by hereticaneue** [comment]
Woohoo! I'd be happy to take care of the pull request, but I wasn't sure actually how to handle the second part of this. I didn't see a public folder in the repo, so I'm not sure where to upload the file / how to include the favicon.

**Comment by AryanJ-NYC** [comment]
Feel free to make a `public` folder in the root of this repo. Then you can configure `.doczrc` to look similar to [the example linked in the OP](https://github.com/doczjs/docz/issues/39#issuecomment-485516734).

**Comment by hereticaneue** [comment]
Okay, I'm on it! Feel free to assign this issue to me if you like. :)
